services:
  postgres:
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=Driver'
      - 'POSTGRES_PASSWORD=userpostgres'
      - 'POSTGRES_USER=userpostgres'
    ports:
      - '5438:5432'
